=== verebes/xml_form_editor/Peldak/Peldak_regi/Allatorvosi lo/lovasok.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="email">
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9,a-z,A-Z]+)([.,_]([0-9,a-z,A-Z]+))*[@]([0-9,a-z,A-Z]+)([.,_,-]([0-9,a-z,A-Z]+))*[.]([0-9,a-z,A-Z]){2}([0-9,a-z,A-Z])?"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="lovasok">
		<xs:sequence>
			<xs:element ref="lovas" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute ref="selected" use="required"/>
	</xs:complexType>
	<xs:complexType name="lovas">
		<xs:sequence>
			<xs:element ref="nev"/>
			<xs:element ref="email"/>
		</xs:sequence>
		<xs:attribute ref="szam" use="required"/>
	</xs:complexType>
	<xs:attribute name="szam" type="xs:byte"/>
	<xs:attribute name="selected" type="xs:byte"/>
	<xs:element name="nev" type="xs:string"/>
	<xs:element name="email" type="email"/>	
	<xs:element name="lovasok" type="lovasok">
		<xs:key name="identifier">
			<xs:selector xpath="./lovas"/>
			<xs:field xpath="@szam"/>
		</xs:key>
	</xs:element>

	<xs:element name="lovas" type="lovas"/>
</xs:schema>

=== verebes/xml_form_editor/Peldak/Peldak_regi/Allatorvosi lo/lovasok.xml
<lovasok xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lovasok.xsd" selected="1">	
	<lovas szam="1">
		<nev>Jani</nev>
		<email>janigmail.com</email>
	</lovas>
	<lovas szam="2">
		<nev>Irma</nev>
		<email>irma@gmail.com</email>		
	</lovas>
	<lovas szam="3">
		<nev>Tóbiás</nev>
		<email>tobias.tivadat@domain.freemail.hu</email>		
	</lovas>
	<lovas szam="45">
		<nev>Tóbiás</nev>
		<email>tobias.tivadat@domain.freemail.hu</email>		
	</lovas>
<lovas szam="4">
	<nev>Kázmér</nev>
	<email>kazi@freemail.hu</email>
</lovas><lovas szam="5">
	<nev>Tihamér</nev>
	<email>kiss.tihamer@datanet.hu</email>
</lovas><lovas szam="12">
	<nev>Ottó</nev>
	<email>otto@mail.com</email>
</lovas></lovasok>
